name: Publish

on:
  push:
    tags:
      - 'plugin-sdk-v*'
      - 'v*'

jobs:
  publish-plugin-sdk:
    name: Publish Plugin SDK
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/plugin-sdk-v') || startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build plugin-sdk
        working-directory: packages/plugin-sdk
        run: pnpm build

      - name: Run tests
        working-directory: packages/plugin-sdk
        run: pnpm test

      - name: Publish to npm
        working-directory: packages/plugin-sdk
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            packages/plugin-sdk/dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
